name: ileotoktok_mobile
description: Ileotoktok MVP client
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.0
  home_widget: ^0.9.0
  app_links: 6.4.1
  flutter_local_notifications: ^20.1.0
  timezone: ^0.10.1
  flutter_tts: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

dependency_overrides:
  app_links: 6.4.1
